trigger:
  - main

pool:
  vmImage: "windows-latest"

variables:
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  # Restore packages with .NET Core
  - task: NuGetToolInstaller@1
    displayName: "Install NuGet"
  - task: NuGetCommand@2
    displayName: "Restore"
    inputs:
      restoreSolution: "src/*.sln"

  # Build and run tests with .NET Core
  - task: DotNetCoreCLI@2
    displayName: "Build Project"
    inputs:
      command: "build"
      projects: "src/WsprSharp/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: "Build Tests"
    inputs:
      command: "build"
      projects: "tests/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: "Run Tests"
    inputs:
      command: test
      projects: "tests/*.csproj"

  # Rebuild the solution with .NET Core
  - task: DotNetCoreCLI@2
    displayName: "Build Everything"
    inputs:
      command: "build"
      projects: "src/*.sln"
      arguments: "--configuration release"

  # Rebuild the solution with .NET Framework
  #- task: VSBuild@1
  #displayName: "Build Everything"
  #inputs:
  #solution: "src/*.sln"
  #configuration: "release"
